package org.dync.teammeeting.structs;


public enum EventType{
	
	MSG_NET_WORK_TYPE,
	
	MSG_ININT_SUCCESS,
	MSG_ININT_FAILED,
	MSG_SIGNOUT_SUCCESS,
	MSG_SIGNOUT_FAILED,
	MSG_GET_ROOM_LIST_SUCCESS,
	MSG_GET_ROOM_LIST_FAILED,
	
	MSG_APPLY_ROOM_SUCCESS,
	MSG_APPLY_ROOMT_FAILED,
	MSG_DELETE_ROOM_SUCCESS,
	MSG_DELETE_ROOM_FAILED,
	MSG_UPDATE_ROOM_ADD_MEM_NUMBER_SUCCESS,
	MSG_UPDATE_ROOM_ADD_MEM_NUMBER_FAILED,
	MSG_UPDATE_ROOM_Minux_MEM_NUMBER_SUCCESS,
	MSG_UPDATE_ROOM_Minux_MEM_NUMBER_FAILED,
	
	MSG_UPDATE_ROOM_PUSHABLE_SUCCESS,
	MSG_UPDATE_ROOM_PUSHABLE_FAILED,
	MSG_UPDATE_ROOM_ENABLE_SUCCESS,
	MSG_UPDATE_ROOM_ENABLE_FAILED,
	
	MSG_UPDATE_MEET_ROOM_NAME_SUCCESS,
	MSG_UPDATE_MEET_ROOM_NAME_FAILED,
	MSG_GET_MEETING_MSG_LIST_SUCCESS,
	MSG_GET_MEETING_MSG_LIST_FAILED,
	
	MSG_INSERT_MEETING_MSG_SUCCESS,
	MSG_INSERT_MEETING_MSG_FAILED,
	MSG_INSERT_SESSION_MEETING_INFO_SUCCESS,
	MSG_INSERT_SESSION_MEETING_INFO_FAILED,
	
	MSG_UPDATE_SESSION_MEETING_STATUS_SUCCESS,
	MSG_UPDATE_SESSION_MEETING_STATUS_FAILED,
	
	MSG_UPDATE_SESSION_MEETING_ENDTIME_SUCCESS,
	MSG_UPDATE_SESSION_MEETING_ENDTIME_FAILED,
	
	MSG_UPDATE_SESSION_MEETING_NUMBER_SUCCESS,
	MSG_UPDATE_SESSION_MEETING_NUMBER_FAILED,

}
